apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: kierkegaardsmiles/auth
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .
        - image: kierkegaardsmiles/tickets
          context: tickets
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .
        - image: kierkegaardsmiles/client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.js"
                    dest: .
        - image: kierkegaardsmiles/orders
          context: orders
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.js"
                    dest: .
